import pptxgen from "pptxgenjs";

const COLORS = {
  primary: "2563EB",
  secondary: "0F172A",
  text: "334155",
  light: "F8FAFC",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
};

export const generatePpt = async (data) => {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "CortexAI";
  ppt.title = data.title;
  ppt.subject = data.title;
  ppt.company = "CortexAI";
  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
  };

  const addCover = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.background = {
      color: COLORS.primary,
    };
    slide.addShape(ppt.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 0.18,
      fill: {
        color: "60A5FA",
      },
      line: {
        color: "60A5FA",
      },
    });
    slide.addText(data.title, {
      x: 0.7,
      y: 1.7,
      w: 12,
      h: 0.8,
      align: "center",
      color: COLORS.white,
      bold: true,
      fontSize: 28,
    });
    slide.addText(data.subtitle, {
      x: 1,
      y: 2.8,
      w: 11.5,
      h: 0.4,
      align: "center",
      color: "DBEAFE",
      fontSize: 28,
    });
    slide.addText("Generated By KaidoAI", {
      x: 0,
      y: 6.9,
      w: 13.33,
      h: 0.2,
      align: "center",
      color: "BFDBFE",
      fontSize: 10,
    });
  };

  const addContentSlide = (ppt, title, points, slideNumber, totalSlides) => {
    const slide = ppt.addSlide();

    slide.background = {
      color: COLORS.light,
    };

    slide.addShape(ppt.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 0.18,
      fill: {
        color: COLORS.primary,
      },
      line: {
        color: COLORS.primary,
      },
    });

    slide.addText(title, {
      x: 0.7,
      y: 0.55,
      w: 11.9,
      h: 0.55,
      color: COLORS.secondary,
      bold: true,
      fontSize: 25,
      margin: 0,
    });

    slide.addShape(ppt.ShapeType.line, {
      x: 0.7,
      y: 1.25,
      w: 11.9,
      h: 0,
      line: {
        color: COLORS.border,
        width: 1,
      },
    });

    const safePoints = Array.isArray(points) ? points : [];

    const leftPoints = safePoints.slice(0, Math.ceil(safePoints.length / 2));

    const rightPoints = safePoints.slice(Math.ceil(safePoints.length / 2));

    const addPointCard = (items, x) => {
      if (!items.length) return;

      slide.addShape(ppt.ShapeType.roundRect, {
        x,
        y: 1.65,
        w: 5.75,
        h: 4.65,
        rectRadius: 0.08,
        fill: {
          color: COLORS.white,
        },
        line: {
          color: COLORS.border,
          width: 1,
        },
        shadow: {
          type: "outer",
          color: "CBD5E1",
          opacity: 0.18,
          blur: 2,
          angle: 45,
          distance: 1,
        },
      });

      const text = items.map((point) => ({
        text: typeof point === "string" ? point : point.text || "",
        options: {
          bullet: {
            indent: 18,
          },
          hanging: 4,
          breakLine: true,
          color: COLORS.text,
        },
      }));

      slide.addText(text, {
        x: x + 0.35,
        y: 1.95,
        w: 5.05,
        h: 4,
        fontSize: 17,
        color: COLORS.text,
        breakLine: false,
        valign: "mid",
        margin: 0.05,
        paraSpaceAfterPt: 16,
        fit: "shrink",
      });
    };

    addPointCard(leftPoints, 0.7);
    addPointCard(rightPoints, 6.85);

    slide.addText(`KaidoAI  •  ${slideNumber}/${totalSlides}`, {
      x: 0.7,
      y: 6.85,
      w: 11.9,
      h: 0.25,
      align: "right",
      color: COLORS.muted,
      fontSize: 9,
      margin: 0,
    });
  };

  addCover(ppt, data);

  data?.slides?.forEach((s, i) => {
    addContentSlide(ppt, s.title, s.points, i + 1, data.slides.length);
  });

  addThankYou(ppt);
  return ppt;
};

const addThankYou = (ppt) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.secondary,
  };

  slide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 0.18,
    fill: {
      color: COLORS.primary,
    },
    line: {
      color: COLORS.primary,
    },
  });

  slide.addText("Thank You", {
    x: 0.7,
    y: 2.35,
    w: 11.9,
    h: 0.7,
    align: "center",
    color: COLORS.white,
    bold: true,
    fontSize: 34,
    margin: 0,
  });

  slide.addText("Questions & Discussion", {
    x: 1,
    y: 3.25,
    w: 11.3,
    h: 0.4,
    align: "center",
    color: "BFDBFE",
    fontSize: 18,
    margin: 0,
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 5.1,
    y: 4.05,
    w: 3.1,
    h: 0,
    line: {
      color: "60A5FA",
      width: 2,
    },
  });

  slide.addText("Generated By KaidoAI", {
    x: 0,
    y: 6.85,
    w: 13.33,
    h: 0.25,
    align: "center",
    color: COLORS.muted,
    fontSize: 10,
    margin: 0,
  });
};
