import PDFDocument from "pdfkit";

export const generatePdf = (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "KaidoAI",
        Title: data.title,
        Creator: "KaidoAI",
      },
    });

    const chunks = [];

    doc.on("data", (chunk) => {
      chunks.push(chunk);
    });

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);

    doc
      .fontSize(24)
      .fillColor("#111827")
      .font("Helvetica-Bold")
      .text(data.title, {
        align: "center",
      });

    doc.moveDown(2);

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .fillColor("#6B7280")
      .text(data.subtitle, {
        align: "center",
      });

    doc.moveDown(2);

    data?.sections?.forEach((section) => {
      doc.fontSize(16).font("Helvetica-Bold").text(section.heading);

      doc.moveDown(0.5);

      section?.points?.forEach((p) => {
        doc
          .fontSize(12)
          .fillColor("#111827")
          .font("Helvetica-Bold")
          .text("• " + p, { lineGap: 5 });
      });
      doc.moveDown(1.5);
    });

    doc.moveDown();

    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .fillColor("#6B7280")
      .text("Generated By Kaido AI", {
        align: "center",
      });

    doc.end();
  });
};
